version: "3"

services:
  webserver:
    build: 
      context: ./src/bin/webserver
    container_name: 'png-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./src/www}:/var/www/campustreks/html
      - ${PHP_INI-./src/config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./src/config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./src/logs/apache2}:/var/log/apache2
  mysql:
    build: ./src/bin/mysql
    container_name: 'png-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./src/data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./src/logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: png
      MYSQL_USER: png
      MYSQL_PASSWORD: png
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'png-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - /sessions
  redis:
    container_name: 'png-redis'
    image: redis:latest
    ports:
      - "6379:6379"